name: Test
on: push

jobs:
  build:
    name: Clone 
    runs-on: ubuntu-latest
    steps:            
      - uses: php-actions/composer@master
        with:
          command: global require "squizlabs/php_codesniffer=*"
      - name: setup
        uses: actions/checkout@v2
        with:
          repository: nursanamar/PHP_CodeSniffer_OpenCart
          path: standard
      - name: prepere code
        uses: actions/checkout@v2
        with:
          path: code
      - name: test lint
        run: ls $GITHUB_WORKSPACE