name: Test
on: push

jobs:
  build:
    name: Clone 
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v2
        with:
          repository: nursanamar/PHP_CodeSniffer_OpenCart
          path: standard
      - name: list
        run: ls $GITHUB_WORKSPACE