name: Test
on: push

jobs:
  build:
    name: Check coding standard 
    runs-on: ubuntu-latest
    steps:            
      - name: get coding standard
        uses: actions/checkout@v2
        with:
          repository: nursanamar/PHP_CodeSniffer_OpenCart
          path: standard
      - name: get current code
        uses: actions/checkout@v2
        with:
          path: code
      - name: PHPCS check
        uses: nursanamar/phpcs-action@master
        with:
          installed_paths: '${{ github.workspace }}/standard'
          target_path: '${{ github.workspace }}/code'
