name: Test
on: push

jobs:
  build:
    name: Clone 
    runs-on: ubuntu-latest
    steps:            
      - name: setup
        uses: actions/checkout@v2
        with:
          repository: nursanamar/PHP_CodeSniffer_OpenCart
          path: standard
      - name: prepere code
        uses: actions/checkout@v2
        with:
          path: code
      - name: test lint
        run: ls $GITHUB_WORKSPACE
      - name: PHPCS check
        uses: nursanamar/phpcs-action@master
        with:
          installed_paths: '${{ github.workspace }}/standard'
          target_path: ${{ github.workspace }}/code'
